Repository AaronSosaRamos/gemini-dynamo-frontend, pull requests merged in 2024-09, with the labels that each got.

#6 new main screen imp.
  app/dynamo/page.tsx
  app/page.tsx
  components/Header.tsx
  components/MainScreen.tsx
  package-lock.json
  package.json
Labels: documentation, enhancement, good first issue

#7 updated main screen
  app/concept-retriever/page.tsx
  components/Header.tsx
  components/MainScreen.tsx
Labels: documentation, enhancement

#8 fixed bug imp.
  components/MainScreen.tsx
Labels: bug, enhancement, help wanted

#9 Feature/structured data study
  app/concept-retriever/page.tsx
  app/structured-data-study/page.tsx
  components/KeyConceptRetriever.tsx
  components/structured-data-study/ConceptList.tsx
  components/structured-data-study/SturcturedDataStudyForm.tsx
  package.json
  yarn.lock
Labels: documentation, enhancement, help wanted, good first issue

#10 Feature/semantic analysis
  app/semantic-analysis/page.tsx
  app/structured-data-study/page.tsx
  components/semantic-analysis/SemanticAnalysisForm.tsx
  components/semantic-analysis/SemanticAnalysisResult.tsx
  components/structured-data-study/StructuredDataStudyForm.tsx
  components/structured-data-study/SturcturedDataStudyForm.tsx
Labels: documentation, enhancement, help wanted, good first issue

#11 new topic clustering imp.
  app/topic-clustering/page.tsx
  components/topic-clustering/ClusteringResult.tsx
  components/topic-clustering/TopicClusteringForm.tsx
Labels: documentation, enhancement, help wanted, good first issue

#12 Feature/relation mapping
  app/relation-mapping/page.tsx
  app/semantic-analysis/page.tsx
  components/relation-mapping/RelationMappingForm.tsx
  components/relation-mapping/RelationMappingResult.tsx
  components/structured-data-study/StructuredDataStudyForm.tsx
Labels: documentation, enhancement, help wanted, good first issue

#13 new sentiment analysis imp.
  app/sentiment-analysis/page.tsx
  components/sentiment-analysis/SentimentAnalysisForm.tsx
  components/sentiment-analysis/SentimentAnalysisResult.tsx
Labels: documentation, enhancement, help wanted

#14 feature/final-main-screen
  components/MainScreen.tsx
Labels: documentation, enhancement, help wanted

#15 Update favicon.ico
  app/favicon.ico
Labels: documentation, enhancement, good first issue
